# fly.toml app configuration file generated for support-cafe-master-fly on 2026-04-10T15:53:52+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
#
app = 'support-cafe-master-fly'
primary_region = 'sin'

kill_signal = "SIGTERM"
kill_timeout = "30s"

[deploy]
  strategy = "rolling"
  max_unavailable = 1

[experimental]

[build]

[[services]]
  internal_port = 443
  protocol = "tcp"
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[services.ports]]
  port = 443
  handlers = []

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 512
