// This module is auto-generated by endpoint-gen.
// Run: endpoint-gen --config-dir config/
// The generated file is copied to src/codegen/model.rs
//
// Until endpoint-gen is run, this file re-exports from the checked-in model.rs.
// After running endpoint-gen, the generated model.rs will override this.

pub mod model;
